# Generated by Django 5.2.4 on 2025-07-29 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G')], default='V', max_length=1)),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('id_type', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text="Número de factura único, ej: 'A-000001'", max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE_PAGO', max_length=20)),
                ('shipping_status', models.CharField(choices=[('PENDIENTE_DESPACHO', 'Pendiente para Despacho'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADA', 'Entregada'), ('DEVUELTA', 'Devuelta')], default='PENDIENTE_DESPACHO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_invoices', to='api.office')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_invoices', to='api.office')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to='api.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invoices', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso real en Kg', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
            ],
        ),
    ]
