# Generated by Django 5.2.4 on 2025-07-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Transporte Alianza 2025 C.A.', max_length=255)),
                ('rif', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='Tasa de IVA en porcentaje (ej: 16.0)', max_digits=5)),
                ('bcv_rate', models.DecimalField(decimal_places=2, default=36.5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rif', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('office', models.ForeignKey(help_text='Ubicación del bien', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.office')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Ej: 'Creación de factura', 'Inicio de sesión'", max_length=255)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales, como el ID del objeto afectado.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
