# Generated by Django 5.2.4 on 2025-07-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assetcategory_companyinfo_supplier_asset_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Ruta', 'En Ruta'), ('En Mantenimiento', 'En Mantenimiento')], default='Disponible', max_length=20),
        ),
    ]
