# Generated by Django 5.2.4 on 2025-07-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehicle_driver_vehicle_imageurl_alter_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
