# Generated by Django 5.2.4 on 2025-08-12 21:00

from django.db import migrations

# Lista completa de permisos de la aplicación
ALL_PERMISSIONS = {
    # Dashboard
    'dashboard.view': 'Ver el Dashboard',
    # Shipping Guide (Invoice Creation)
    'shipping-guide.view': 'Ver la página de Crear Factura',
    # Invoices
    'invoices.view': 'Ver lista de Facturas',
    'invoices.create': 'Crear nuevas Facturas',
    'invoices.edit': 'Editar Facturas existentes',
    'invoices.void': 'Anular Facturas',
    'invoices.delete': 'Eliminar Facturas (anuladas)',
    'invoices.changeStatus': 'Cambiar estado de pago/envío',
    # Clients
    'clientes.view': 'Ver Clientes',
    'clientes.create': 'Crear Clientes',
    'clientes.edit': 'Editar Clientes',
    'clientes.delete': 'Eliminar Clientes',
    # Suppliers
    'proveedores.view': 'Ver Proveedores',
    'proveedores.create': 'Crear Proveedores',
    'proveedores.edit': 'Editar Proveedores',
    'proveedores.delete': 'Eliminar Proveedores',
    # Fleet
    'flota.view': 'Ver Flota y Remesas',
    'flota.create': 'Crear Vehículos',
    'flota.edit': 'Editar Vehículos',
    'flota.delete': 'Eliminar Vehículos',
    'flota.dispatch': 'Despachar y finalizar viajes',
    # Accounting
    'libro-contable.view': 'Ver Libro Contable',
    'libro-contable.create': 'Crear Gastos',
    'libro-contable.edit': 'Editar Gastos',
    'libro-contable.delete': 'Eliminar Gastos',
    # Inventory
    'inventario.view': 'Ver módulo de Inventario',
    'inventario-envios.view': 'Ver Inventario de Envíos',
    'inventario-bienes.view': 'Ver Inventario de Bienes',
    'inventario-bienes.create': 'Crear Bienes',
    'inventario-bienes.edit': 'Editar Bienes',
    'inventario-bienes.delete': 'Eliminar Bienes',
    'bienes-categorias.view': 'Ver Categorías de Bienes',
    'bienes-categorias.create': 'Crear Categorías de Bienes',
    'bienes-categorias.edit': 'Editar Categorías de Bienes',
    'bienes-categorias.delete': 'Eliminar Categorías de Bienes',
    # Reports
    'reports.view': 'Ver Reportes',
    # System & Audit
    'system.view': 'Ver página de Sistema',
    'system.cleanup': 'Usar herramienta de limpieza',
    'system.backupRestore': 'Realizar respaldos y restauraciones',
    'auditoria.view': 'Ver Auditoría',
    # Configuration
    'configuracion.view': 'Ver página de Configuración',
    'config.company.edit': 'Editar datos de la empresa',
    'config.users.manage': 'Gestionar usuarios y roles',
    'config.roles.manage': 'Gestionar roles y permisos',
    'config.users.edit_protected': 'Editar usuarios protegidos (admin/soporte)',
    'config.users.manage_tech_users': 'Gestionar usuarios de Soporte Técnico',
    # Parameters (sub-config pages)
    'categories.view': 'Ver Categorías de Mercancía',
    'categories.create': 'Crear Categorías de Mercancía',
    'categories.edit': 'Editar Categorías de Mercancía',
    'categories.delete': 'Eliminar Categorías de Mercancía',
    'offices.view': 'Ver Oficinas y Sucursales',
    'offices.create': 'Crear Oficinas',
    'offices.edit': 'Editar Oficinas',
    'offices.delete': 'Eliminar Oficinas',
    'shipping-types.view': 'Ver Tipos de Envío',
    'shipping-types.create': 'Crear Tipos de Envío',
    'shipping-types.edit': 'Editar Tipos de Envío',
    'shipping-types.delete': 'Eliminar Tipos de Envío',
    'payment-methods.view': 'Ver Formas de Pago',
    'payment-methods.create': 'Crear Formas de Pago',
    'payment-methods.edit': 'Editar Formas de Pago',
    'payment-methods.delete': 'Eliminar Formas de Pago',
}

ROLES_PERMISSIONS = {
    'Operador': [
        'dashboard.view', 'shipping-guide.view', 'invoices.view', 'invoices.create', 
        'invoices.edit', 'invoices.changeStatus', 'clientes.view', 'clientes.create', 
        'clientes.edit', 'proveedores.view', 'proveedores.create', 'proveedores.edit', 
        'flota.view', 'flota.create', 'flota.edit', 'flota.dispatch', 'libro-contable.view', 
        'libro-contable.create', 'libro-contable.edit', 'inventario.view', 
        'inventario-envios.view', 'inventario-bienes.view', 'bienes-categorias.view', 
        'reports.view', 'auditoria.view', 'configuracion.view',
    ],
    'Administrador': [
        'dashboard.view', 'shipping-guide.view', 'invoices.view', 'invoices.create', 
        'invoices.edit', 'invoices.changeStatus', 'invoices.void', 'clientes.view', 
        'clientes.create', 'clientes.edit', 'clientes.delete', 'proveedores.view', 
        'proveedores.create', 'proveedores.edit', 'proveedores.delete', 'flota.view', 
        'flota.create', 'flota.edit', 'flota.delete', 'flota.dispatch', 'libro-contable.view', 
        'libro-contable.create', 'libro-contable.edit', 'libro-contable.delete', 
        'inventario.view', 'inventario-envios.view', 'inventario-bienes.view', 
        'inventario-bienes.create', 'inventario-bienes.edit', 'inventario-bienes.delete', 
        'bienes-categorias.view', 'bienes-categorias.create', 'bienes-categorias.edit', 
        'bienes-categorias.delete', 'reports.view', 'auditoria.view', 'configuracion.view',
        'config.company.edit', 'config.users.manage', 'config.roles.manage', 
        'categories.view', 'categories.create', 'categories.edit', 'categories.delete',
        'offices.view', 'offices.create', 'offices.edit', 'offices.delete',
        'shipping-types.view', 'shipping-types.create', 'shipping-types.edit', 'shipping-types.delete',
        'payment-methods.view', 'payment-methods.create', 'payment-methods.edit', 'payment-methods.delete',
    ],
    'Soporte Técnico': list(ALL_PERMISSIONS.keys())
}

def seed_data(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')
    Role = apps.get_model('api', 'Role')

    # Crear todos los permisos
    for key, description in ALL_PERMISSIONS.items():
        Permission.objects.get_or_create(key=key, defaults={'description': description})

    # Crear roles y asignar permisos
    for role_name, permission_keys in ROLES_PERMISSIONS.items():
        role, created = Role.objects.get_or_create(name=role_name)
        permissions_to_add = Permission.objects.filter(key__in=permission_keys)
        role.permissions.set(permissions_to_add)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_vehicle_imageurl_vehicle_image'), # Asegúrate que este sea el nombre de tu última migración real
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]