# Generated by Django 5.2.4 on 2025-08-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_expensecategory_paymentmethod_shippingtype_and_more'),
        ('api', '0009_seed_permissions_and_roles'),
    ]

    operations = [
    ]
