# Generated by Django 5.2.4 on 2025-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20250812_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_license',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
