# Generated by Django 5.2.4 on 2025-08-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_companyinfo_logo_url_companyinfo_login_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igtf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ipostel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_currency',
            field=models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares')], default='VES', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentmethod'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('flete-pagado', 'Flete Pagado'), ('flete-destino', 'Flete a Destino')], default='flete-pagado', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shippingtype'),
        ),
    ]
